### PR TITLE
adds bind

### PR DESCRIPTION
**Pull request by stoeffel**
@1-liners/owners how do you like the api of this? Would you change the order of the function and the context?

### CODE REVIEW

**Comment by tomekwi** [comment]
Hmm, to me the function is data. So perhaps `bind(thisArg, args, fun)`?

**Comment by hemanth** [comment]
`thisArg` is optional.

**Comment by stoeffel** [comment]
@hemanth 

> 3. Each function shall have a stable number of arguments

@tomekwi makes sense I will change it asab.

**Comment by stoeffel** [comment]
:checkered_flag:

**Pull request merged**
