### PR TITLE
adds object-assign plugin so we don't need a global ponyfill

### PR DESCRIPTION
**Pull request by stoeffel**
resolves https://github.com/studio-b12/tiny-error/commit/f900f3daea78d847c6a4e1f9372b3c9b2de31e18

:warning: not ready to merge. it messes up our codecoverage. 
Does anyone know how we can exlude this?
screen shot 2015-06-09 at 17 04 03

### CODE REVIEW

**Comment by tomekwi** [comment]
https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.md

**Comment by tomekwi** [comment]
No idea how to stick the `/* istanbul ignore next */` in there. Perhaps that would have to be solved upstream?

**Comment by stoeffel** [comment]
I will make a pr in babel-plugin-object-assign. maybe he will merge it

**Comment by stoeffel** [comment]
I moved to babel-runtime.

:checkered_flag:

**Comment by stoeffel** [comment]
maybe we could bundle the runtime with browserify

**Comment by tomekwi** [comment]
> maybe we could bundle the runtime with browserify

I wouldn’t do that. The bundled source of `extend` grows from ~2 kiB to over 8 kiB (vs 500 B transpiled and 360 B raw).

And it doesn’t look too good:

```
/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};

/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {

/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId])
/******/ 			return installedModules[moduleId].exports;

/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			exports: {},
/******/ 			id: moduleId,
/******/ 			loaded: false
/******/ 		};

/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);

/******/ 		// Flag the module as loaded
/******/ 		module.loaded = true;

/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}


/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;

/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;

/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";

/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(0);
/******/ })
/************************************************************************/
/******/ ([
/* 0 */
/***/ function(module, exports, __webpack_require__) {

	/**
	 * @module 1-liners/extend
	 *
	 * @description
	 *
	 * Returns a copy of `object`, extended by `extension`.
	 *
	 * @example
	 *
	 * 	const extend = require('1-liners/extend');
	 *
	 * 	const object = {id: 1};
	 *
	 * 	extend({ name: 'stoeffel' }, object);  // => { id: 1, name: 'stoeffel' }
	 *
	 */
	"use strict";

	var _Object$assign = __webpack_require__(1)["default"];

	exports.__esModule = true;

	exports["default"] = function (extension, object) {
	  return _Object$assign({}, object, extension);
	};

	module.exports = exports["default"];

/***/ },
/* 1 */
/***/ function(module, exports, __webpack_require__) {

	module.exports = { "default": __webpack_require__(2), __esModule: true };

/***/ },
/* 2 */
/***/ function(module, exports, __webpack_require__) {

	__webpack_require__(3);
	module.exports = __webpack_require__(4).core.Object.assign;

/***/ },
/* 3 */
/***/ function(module, exports, __webpack_require__) {

	// 19.1.3.1 Object.assign(target, source)
	var $def = __webpack_require__(5);
	$def($def.S, 'Object', {assign: __webpack_require__(6)});

/***/ },
/* 4 */
/***/ function(module, exports, __webpack_require__) {

	'use strict';
	var global = typeof self != 'undefined' ? self : Function('return this')()
	  , core   = {}
	  , defineProperty = Object.defineProperty
	  , hasOwnProperty = {}.hasOwnProperty
	  , ceil  = Math.ceil
	  , floor = Math.floor
	  , max   = Math.max
	  , min   = Math.min;
	// The engine works fine with descriptors? Thank's IE8 for his funny defineProperty.
	var DESC = !!function(){
	  try {
	    return defineProperty({}, 'a', {get: function(){ return 2; }}).a == 2;
	  } catch(e){ /* empty */ }
	}();
	var hide = createDefiner(1);
	// 7.1.4 ToInteger
	function toInteger(it){
	  return isNaN(it = +it) ? 0 : (it > 0 ? floor : ceil)(it);
	}
	function desc(bitmap, value){
	  return {
	    enumerable  : !(bitmap & 1),
	    configurable: !(bitmap & 2),
	    writable    : !(bitmap & 4),
	    value       : value
	  };
	}
	function simpleSet(object, key, value){
	  object[key] = value;
	  return object;
	}
	function createDefiner(bitmap){
	  return DESC ? function(object, key, value){
	    return $.setDesc(object, key, desc(bitmap, value));
	  } : simpleSet;
	}

	function isObject(it){
	  return it !== null && (typeof it == 'object' || typeof it == 'function');
	}
	function isFunction(it){
	  return typeof it == 'function';
	}
	function assertDefined(it){
	  if(it == undefined)throw TypeError("Can't call method on  " + it);
	  return it;
	}

	var $ = module.exports = __webpack_require__(7)({
	  g: global,
	  core: core,
	  html: global.document && document.documentElement,
	  // http://jsperf.com/core-js-isobject
	  isObject:   isObject,
	  isFunction: isFunction,
	  that: function(){
	    return this;
	  },
	  // 7.1.4 ToInteger
	  toInteger: toInteger,
	  // 7.1.15 ToLength
	  toLength: function(it){
	    return it > 0 ? min(toInteger(it), 0x1fffffffffffff) : 0; // pow(2, 53) - 1 == 9007199254740991
	  },
	  toIndex: function(index, length){
	    index = toInteger(index);
	    return index < 0 ? max(index + length, 0) : min(index, length);
	  },
	  has: function(it, key){
	    return hasOwnProperty.call(it, key);
	  },
	  create:     Object.create,
	  getProto:   Object.getPrototypeOf,
	  DESC:       DESC,
	  desc:       desc,
	  getDesc:    Object.getOwnPropertyDescriptor,
	  setDesc:    defineProperty,
	  setDescs:   Object.defineProperties,
	  getKeys:    Object.keys,
	  getNames:   Object.getOwnPropertyNames,
	  getSymbols: Object.getOwnPropertySymbols,
	  assertDefined: assertDefined,
	  // Dummy, fix for not array-like ES3 string in es5 module
	  ES5Object: Object,
	  toObject: function(it){
	    return $.ES5Object(assertDefined(it));
	  },
	  hide: hide,
	  def: createDefiner(0),
	  set: global.Symbol ? simpleSet : hide,
	  each: [].forEach
	});
	/* eslint-disable no-undef */
	if(typeof __e != 'undefined')__e = core;
	if(typeof __g != 'undefined')__g = global;

/***/ },
/* 5 */
/***/ function(module, exports, __webpack_require__) {

	var $          = __webpack_require__(4)
	  , global     = $.g
	  , core       = $.core
	  , isFunction = $.isFunction;
	function ctx(fn, that){
	  return function(){
	    return fn.apply(that, arguments);
	  };
	}
	// type bitmap
	$def.F = 1;  // forced
	$def.G = 2;  // global
	$def.S = 4;  // static
	$def.P = 8;  // proto
	$def.B = 16; // bind
	$def.W = 32; // wrap
	function $def(type, name, source){
	  var key, own, out, exp
	    , isGlobal = type & $def.G
	    , isProto  = type & $def.P
	    , target   = isGlobal ? global : type & $def.S
	        ? global[name] : (global[name] || {}).prototype
	    , exports  = isGlobal ? core : core[name] || (core[name] = {});
	  if(isGlobal)source = name;
	  for(key in source){
	    // contains in native
	    own = !(type & $def.F) && target && key in target;
	    if(own && key in exports)continue;
	    // export native or passed
	    out = own ? target[key] : source[key];
	    // prevent global pollution for namespaces
	    if(isGlobal && !isFunction(target[key]))exp = source[key];
	    // bind timers to global for call from export context
	    else if(type & $def.B && own)exp = ctx(out, global);
	    // wrap global constructors for prevent change them in library
	    else if(type & $def.W && target[key] == out)!function(C){
	      exp = function(param){
	        return this instanceof C ? new C(param) : C(param);
	      };
	      exp.prototype = C.prototype;
	    }(out);
	    else exp = isProto && isFunction(out) ? ctx(Function.call, out) : out;
	    // export
	    exports[key] = exp;
	    if(isProto)(exports.prototype || (exports.prototype = {}))[key] = out;
	  }
	}
	module.exports = $def;

/***/ },
/* 6 */
/***/ function(module, exports, __webpack_require__) {

	var $        = __webpack_require__(4)
	  , enumKeys = __webpack_require__(8);
	// 19.1.2.1 Object.assign(target, source, ...)
	/* eslint-disable no-unused-vars */
	module.exports = Object.assign || function assign(target, source){
	/* eslint-enable no-unused-vars */
	  var T = Object($.assertDefined(target))
	    , l = arguments.length
	    , i = 1;
	  while(l > i){
	    var S      = $.ES5Object(arguments[i++])
	      , keys   = enumKeys(S)
	      , length = keys.length
	      , j      = 0
	      , key;
	    while(length > j)T[key = keys[j++]] = S[key];
	  }
	  return T;
	};

/***/ },
/* 7 */
/***/ function(module, exports, __webpack_require__) {

	module.exports = function($){
	  $.FW   = false;
	  $.path = $.core;
	  return $;
	};

/***/ },
/* 8 */
/***/ function(module, exports, __webpack_require__) {

	var $ = __webpack_require__(4);
	module.exports = function(it){
	  var keys       = $.getKeys(it)
	    , getDesc    = $.getDesc
	    , getSymbols = $.getSymbols;
	  if(getSymbols)$.each.call(getSymbols(it), function(key){
	    if(getDesc(it, key).enumerable)keys.push(key);
	  });
	  return keys;
	};

/***/ }
/******/ ]);
```

**Comment by stoeffel** [comment]
yop you are right.

**Comment by tomekwi** [comment]
I think it’s still better to use this babel-blabla-assign thing

**Comment by stoeffel** [comment]
I am pro plugin too. But the plugin should work with auxiliary comment 'Istanbul ignore next', which it doesn't at the moment. I am pretty swampt with work at the moment so I don't know when I will have time (Maybe next week) to either create a PR or a own plugin.

**Comment by tomekwi** [comment]
BTW, if you find the time to do a PR, we can instantly switch to your version without waiting for the upstream merge. Like we did in <https://github.com/1-liners/1-liners/commit/6f51df002a93b09a35622bb5e88a2dc9a9821163>.

**Comment by tomekwi** [comment]
:( there’s a similar problem with `array.includes`. https://github.com/studio-b12/doxie.render/commit/ffa4f9809db8e2b5d9d89e846cad5a8ac347a4f1

Just saying, it’s nothing urgent.

**Comment by stoeffel** [comment]
Hmm... I'm still not totally happy with the plugin. We would need a plugin that replaces all array.includes and array.assign. When I find time to learn how to write a babel-plugin I may write one that inlines all the babel helper functions.

**Comment by stoeffel** [comment]
@tomekwi fyi maybe you already know. I made a PR and will create a edge branch of babel-plugin-object-assign this evening.

**Comment by tomekwi** [comment]
:+1: great! Let me know if you find a good workflow with edge branch + build step – I’ve always struggled and never managed to get it right: https://github.com/1-liners/1-liners/commit/d0d5eef92c66e39bee62f1647e9f0666efbd8a8c

**Comment by stoeffel** [comment]
:checkered_flag: 

transpiled function looks like this:

```js
/**
 * @module 1-liners/drop
 *
 * @description
 *
 * Creates a copy of the `object` without the given `props`.
 *
 * @example
 *
 * 	const drop = require('1-liners/drop');
 *
 * 	const object = {foo: 1, bar: 2, baz: 3};
 *
 * 	drop(['foo', 'baz'], object);  // => {bar: 2}
 * 	object;                        // => {foo: 1, bar: 2, baz: 3}
 *
 */
"use strict";

exports.__esModule = true;
// istanbul ignore next

var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };

exports["default"] = function (props, object) {
  return Object.keys(object).reduce(function (res, k) {
    // istanbul ignore next

    var _ref;

    return _extends(res, props.includes(k) ? null : (_ref = {}, _ref[k] = object[k], _ref));
  }, {});
};

module.exports = exports["default"];

```

:warning: we have to change the dep back to the original as soon as https://github.com/babel-plugins/babel-plugin-object-assign/pull/3 is merged

**Comment by tomekwi** [comment]
:+1: I’ll check it out tomorrow

**Comment by tomekwi** [comment]
Works like a charm! Thank you :)

**Comment by tomekwi** [comment]
Hmm, I tried doing some maintenance and realized that `npm run precommit` wipes the table of contents. After digging a little deeper I realized that:

```
$ babel-node ./utils/createDocs.js
…/1-liners/node_modules/babel-plugin-object-assign/lib/index.js:11
  return new Plugin("object-assign", {
         ^
TypeError: undefined is not a function
    at exports.default (…/1-liners/node_modules/babel-plugin-object-assign/lib/index.js:11:10)
    at Function.memoisePluginContainer (~/.nvm/versions/node/v0.12.4/lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/plugin-manager.js:46:23)
    at PluginManager.add (~/.nvm/versions/node/v0.12.4/lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/plugin-manager.js:131:30)
    at File.buildTransformers (~/.nvm/versions/node/v0.12.4/lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/index.js:290:21)
    at new File (~/.nvm/versions/node/v0.12.4/lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/index.js:148:10)
    at TransformerPipeline.transform (~/.nvm/versions/node/v0.12.4/lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/transformer-pipeline.js:96:16)
    at Object.transformFileSync (~/.nvm/versions/node/v0.12.4/lib/node_modules/babel/node_modules/babel-core/lib/babel/api/node.js:108:42)
    at compile (~/.nvm/versions/node/v0.12.4/lib/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:109:20)
    at normalLoader (~/.nvm/versions/node/v0.12.4/lib/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:160:14)
    at Object.require.extensions.(anonymous function) [as .js] (~/.nvm/versions/node/v0.12.4/lib/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:173:7)
```

It might be an issue with babel-plugin-object-assign – but perhaps you know what’s wrong @stoeffel

**Comment by stoeffel** [comment]
The problem is that `babel-node` also uses the `.babelrc` which seams doesn't work. we may need to use the command line options instead of `.babelrc` could you try that?

**Comment by stoeffel** [comment]
> we may need to use the command line options instead of .babelrc

for `npm run compile`

**Comment by tomekwi** [comment]
TBH I’m a bit short of time now. I’ve already spent a good while to spot the problem. Can you reproduce the problem?

**Comment by stoeffel** [comment]
should be fixed https://github.com/1-liners/1-liners/commit/fd32fb3cf8e9da18cdf90c62d2a5d9108223e35c

**Comment by tomekwi** [comment]
:ok_hand:

**Pull request merged**
