### PR TITLE
adds put

### LINKED ISSUE #84: Add `put`
Like *101/put*.

For example:

```js
(key, value, object) => Object.assign({}, object, {[key]: value});
```

### PR DESCRIPTION
**Pull request by stoeffel**
closes #84

:checkered_flag:

### CODE REVIEW

**Comment by tomekwi** [comment]
Looks good to me! :rocket:

**Comment by stoeffel** [comment]
:smiley: You did most of the work in the issue :+1:

**Comment by tomekwi** [comment]
Yeah, 10 seconds hard work ;)

**Comment by tomekwi** [comment]
The EcmaScript commitee did the hard work here ;)

**Comment by stoeffel** [comment]
hard work

**Comment by tomekwi** [comment]
:D

**Pull request merged**
