### PR TITLE
RegExp functions

### LINKED ISSUE #106: RegExp functions
* [x] [exec](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec)
* [x] [test](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test)
* ~~[toString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/toString) (does it make sense? We have the native `String()`)~~

### PR DESCRIPTION
**Pull request by tomekwi**
Closes #106

### CODE REVIEW

**Comment by tomekwi** [comment]
:checkered_flag:

Had lots of adventures on the way: @7614ba6 @567881c @0080bf7

**Comment by stoeffel** [comment]
Hmmm.... I'm not sure if we should prepend this functions with 'RegExp'? test and exec is not that expressive.... What do you think?

**Comment by tomekwi** [comment]
Good point. I like how all our mirrors of native functions share the name with the original. But I guess `test` and `exec` were poorly named from the very beginning.

But then again, once you write it down in code:

```js
test('haystack', /hay/);
```

… it becomes no less expressive than:

```js
/hay/.test('haystack');
```

**Comment by stoeffel** [comment]
> I guess test and exec were poorly named from the very beginning.

:smile: agreed

> But then again, once you write it down in code

yop, let's keep it this way. one can still rename it on import.

**Comment by tomekwi** [comment]
:+1: I’m shipping then :)

**Pull request merged**
