### PR TITLE
last + butLast

### PR DESCRIPTION
**Pull request by tomekwi**
### pop

Similar to `array.pop()`, but immutable.

```js
import pop from '1-liners/pop';

const array = [1, 2, 3];

pop(array);  // => [1, 2]
array;       // => [1, 2, 3]
```

<div align="right"><sup>
	<a href="../tests/pop.js">Spec</a>
	•
	<a href="../module/pop.js">Source</a>: <code> (array) =&gt; array.slice(0, -1);</code>
</sup></div>

***

### shift

Similar to `array.shift()`, but immutable.

```js
import shift from '1-liners/shift';

const array = [1, 2, 3];

shift(array);  // => [2, 3]
array;         // => [1, 2, 3]
```

<div align="right"><sup>
	<a href="../tests/shift.js">Spec</a>
	•
	<a href="../module/shift.js">Source</a>: <code> (array) =&gt; array.slice(1);</code>
</sup></div>

### CODE REVIEW

**Comment by tomekwi** [comment]
@stoeffel @hemanth I’m just wondering about one thing. `array.pop()` returns a value, not an array – and mutates the array. There’s no simple way to return both the value and the array at the same time.

`value = array.shift()` has its counterpart `value = head(array)`. Maybe `value = array.pop()` should also have something like `value = last(array)` or so?

**Comment by tomekwi** [comment]
:checkered_flag:

**Comment by tomekwi** [comment]
Oops, `shift` looks like it’s the same as `tail`. We need to think it over then.

**Comment by stoeffel** [comment]
Yop lets add pop and last. I like the names head and tail more than shift and first.

**Comment by hemanth** [comment]
Even I vote for `head` and `tail`

**Comment by tomekwi** [comment]
> I like the names head and tail more than shift and first.

Yeah, absolutely :) I rather don’t like `pop` and `last` but have no idea for a better name.

**Comment by stoeffel** [comment]
> I need to release the latest changes to npm

Sure, NP :+1: 

> I’d rather decide on the name

I don't think `last` is a bad name. It says what it does. `pop` on the other hand is not so great.

**Comment by tomekwi** [comment]
Hmm, how about `body` and `butt`? ;)

**Comment by stoeffel** [comment]
haha. I like that!

**Comment by tomekwi** [comment]
:D let’s see what @hemanth has to say. If he’s OK, I get down to business :D

**Comment by hemanth** [comment]
:D `body` is everything expect the `tail`? and `head` would be? What about `neck` :P 

`butt` is bit weird.

**Comment by stoeffel** [comment]
@hemanth see below for an example:

```js
var arr = [1, 2, 3];

body(arr) === [1, 2]
butt(arr) === 3

// this is pretty common in FP
head(arr) === 1 // lisp car
tail(arr) === [2, 3] // lisp cdr
```

How about `butlast` and `last` like in clojure https://clojuredocs.org/clojure.core/butlast?

**Comment by hemanth** [comment]
Yup, got it. I would still vote for `head` and `tail` :)

**Comment by stoeffel** [comment]
`head` and `tail` is not the same as `body/butlast` and `butt/last`.
`Head` and `tail` is already implemented.

**Comment by hemanth** [comment]
Yikes, overlooked it!  `butlast` and `last` makes sense.

**Comment by tomekwi** [comment]
@hemanth the `butt` is opposite the `head` – so it’s the last element. `body` is all but the `butt`.

But I can name it `butLast` and `last` if you think it’s more explicit.

**Comment by stoeffel** [comment]
> But I can name it butLast and last if you think it’s more explicit.

it's less fun but more explicit. Go for it :rocket:

**Comment by tomekwi** [comment]
Haha :D

**Comment by tomekwi** [comment]
### butLast

Return a copy of `array`, without the last item.

```js
import butLast from '1-liners/butLast';

const array = [1, 2, 3];

butLast(array);  // => [1, 2]
array;           // => [1, 2, 3]
```

<div align="right"><sup>
	<a href="../tests/butLast.js">Spec</a>
	•
	<a href="../module/butLast.js">Source</a>: <code> (array) =&gt; array.slice(0, -1);</code>
</sup></div>

***


### last

Returns the last item of `array`.

```js
var last = require('1-liners/last');

last([1, 2, 3]);  // => 3
```

<div align="right"><sup>
	<a href="../tests/last.js">Spec</a>
	•
	<a href="../module/last.js">Source</a>: <code> (array) =&gt; array[array.length - 1];</code>
</sup></div>


***

:checkered_flag:

**Comment by tomekwi** [comment]
@stoeffel by the way, I’ve just learned that our `butLast` is called `init` in Haskell. Should we rename?

**Comment by stoeffel** [comment]
I actually think that butLast describes better what the function does, but
then, it's a function I rarely use. So if you think init is better, then go
for it :smiley:
Am 18.06.2015 15:05 schrieb "Tomek Wiszniewski" <notifications@github.com>:

**Comment by tomekwi** [comment]
> I actually think that butLast describes better what the function does

:+1: just saying.

**Pull request merged**
