### PR TITLE
add babel-plugin-array-includes to convert includes to indexOf >= 0

### PR DESCRIPTION
**Pull request by stoeffel**
@tomekwi how do you like this?

i.e. `drop`
```js
exports["default"] = function (props, object) {
  return Object.keys(object).reduce(function (res, k) {
    // istanbul ignore next

    var _ref;

    return _extends(res, props.indexOf(k) >= 0 ? null : (_ref = {}, _ref[k] = object[k], _ref));
  }, {});
};

// instead of
exports["default"] = function (props, object) {
  return Object.keys(object).reduce(function (res, k) {
    // istanbul ignore next

    var _ref;

    return _extends(res, props.includes(k)? null : (_ref = {}, _ref[k] = object[k], _ref));
  }, {});
};

```

### CODE REVIEW

**Comment by tomekwi** [comment]
Great idea! :+1: :+1:

**Comment by stoeffel** [comment]
Thanks.
Maybe the guys from [babel-plugins](https://github.com/babel-plugins) are interessted to take over the ownership of [babel-plugin-array-includes](https://github.com/stoeffel/babel-plugin-array-includes) or have some input on how to improve the plugin (it was my first :flushed:)?

// cc @sebmck

**Comment by sebmck** [comment]
@stoeffel Seems kinda brittle, `foo.includes` may not always reference an array. You shouldn't be performing on the raw source or dealing with strings at all (it's quite inefficient) and is kinda pointless when you have an AST that removes all that ambiguity.

**Comment by stoeffel** [comment]
@sebmck thanks for the input.

> Seems kinda brittle, foo.includes may not always reference an array

Yop, you are right. But it also works with strings and typedarrays since they also have `indexOf`.

> You shouldn't be performing on the raw source or dealing with strings at all (it's quite inefficient) and is kinda pointless when you have an AST that removes all that ambiguity.

Will try to improve that.

Thanks again for your feedback.

**Comment by sebmck** [comment]
@stoeffel 

> Yop, you are right. But it also works with strings and typedarrays since they also have `indexOf`.

Was more referring to cases like:

```javascript
class Foo {
  includes() {
    return "magic;
  }

  indexOf() {
    throw new Error("oi");
  }
}

new Foo().includes();
```

**Comment by stoeffel** [comment]
@sebmck I see. Thanks. I will have to check if it's an array.

I started rewriting the hole thing.

Does this look better?

```js
      CallExpression: function (node, parent, scope, file) {
        var callee = this.get('callee');
        if (callee.node.property && callee.node.property.name === 'includes') {
          callee.node.property.name = 'indexOf';
//TODO check if array
          return t.logicalExpression(">=", node, t.literal(0));
        }
      }
```

**Comment by sebmck** [comment]
Something like:

```javascript
CallExpression: function (node, parent, scope, file) {
  var callee = this.get('callee');
  if (
    // this makes sure that `foo[includes]()` isn't matched
    callee.isMemberExpression({ computed: false }) &&

    // verify that the property of the member expression is `include`
    callee.get("property").isIdentifier({ name: "includes") }) &&
    
    // this will resolve and infer the type of a certain value, this isn't very sophisticated which means if you want this to match you have to either:
    //
    //  1. assign an array but never reassign it (constant bindings)
    //     
    //     var arr = [];
    //     arr; // we can determine this is an array
    //    
    //     var arr = [];
    //     arr = bar(arr); // can't be 100% confident now
    // 
    //  2. flow: give the binding an Array type
    //   
    //     var arr: Array = bar(); // even though we don't know what is producing this value, we've explictly provided the type
    //     arr = foo(); // since the type is explicit we don't deopt on reassignments
    //     arr; // yup! this is an Array
    //
    //  3. flow: use a typecast expression
    //
    //     (foo(): Array); // typecast expressions are a way of annotating the return type of an expression
    //
    callee.get("object").isGenericType("Array")
  ) {
    callee.node.property.name = 'indexOf';
    return t.logicalExpression(">=", node, t.literal(0));
  }
}
```

Should be good enough.

**Comment by stoeffel** [comment]
@sebmck Thanks a lot for your help, I did update the plugin.

**Comment by stoeffel** [comment]
@tomekwi @hemanth should we merge this?

**Comment by stoeffel** [comment]
I will rebase asap

**Comment by stoeffel** [comment]
rebased :checkered_flag:

**Pull request merged**
