### PR TITLE
extend -> assign

### PR DESCRIPTION
**Pull request by stoeffel**
- renames extend
- simplifies code (uses deconstructing instead of Object.assign)
- adds new testcase
- improves the docs

### CODE REVIEW

**Comment by stoeffel** [comment]
opinions? @1-liners/maintainers

**Comment by tomekwi** [comment]
Great! Breaking change though – we should hop on to semver shouldn’t we? 1.0.0?

**Comment by stoeffel** [comment]
Yop, agreed. Let's publish this with 1.0.0

**Comment by hemanth** [comment]
:sun_with_face:

**Pull request merged**
