### PR TITLE
added pipeAll()

### PR DESCRIPTION
**Pull request by guumaster**
I don't know about function readability and it doesn't have a fixed number of parameter.

### CODE REVIEW

**Comment by stoeffel** [comment]
It should take an array of functions not n functions.

**Comment by guumaster** [comment]
oh, ok. `pipeAll([fnArray])` instead of `pipeAll(fn1, fn2, fn3)` would have an arity of one. I've missed that. I'll correct both PRs.

**Comment by guumaster** [comment]
also squashed commits

**Comment by stoeffel** [comment]
pipe

**Comment by guumaster** [comment]
Totally mesmerizing

**Pull request merged**
