### PR TITLE
Add `extend`

### PR DESCRIPTION
**Pull request by tomekwi**
### extend

Returns a copy of `object`, extended by `extension`.

```js
const extend = require('1-liners/extend');

const object = {id: 1};

extend({ name: 'stoeffel' } object);  // => { id: 1, name: 'stoeffel' }
```

<div align="right"><sup>
	<a href="../tests/extend.js">Spec</a>
	•
	<a href="../module/extend.js">Source</a>: <code> (extension, object) =&gt; Object.assign({}, object, extension);</code>
</sup></div>

### CODE REVIEW

**Comment by tomekwi** [comment]
A companion to `put`.

:checkered_flag: should I merge and release?

**Comment by tomekwi** [comment]
Now :checkered_flag: for good :)

**Comment by tomekwi** [comment]
100<sup>th</sup> issue BTW :D

:birthday:

:tada:

**Comment by stoeffel** [comment]
Yeah #100 :cake: 

Yop merge and release.

**Comment by tomekwi** [comment]
:ok_hand:  Released as 0.2.10

**Comment by stoeffel** [comment]
nice :fireworks: good night.

**Comment by tomekwi** [comment]
Good night :)

**Pull request merged**
