### PR TITLE
Readme update

### PR DESCRIPTION
**Pull request by tomekwi**
CC: @stoeffel @hemanth

### CODE REVIEW

**Comment by tomekwi** [comment]
:+1:

**Comment by hemanth** [comment]
:+1:

**Comment by stoeffel** [comment]
Sweet!!! Does this close #62 or is there still some thing open?

**Comment by tomekwi** [comment]
Closes #62 

I guess :)

**Comment by tomekwi** [comment]
😕

I thought my comment would close the issue. I’m still confused by all these fancy features of GitHub :)

**Pull request merged**
