### PR TITLE
Add String repeat, normalize, trim, search, localeCompare, includes

### PR DESCRIPTION
**Pull request by huei90**

### CODE REVIEW

**Comment by tomekwi** [comment]
:+1: Wow! Great!

Looks like ready to :ship: to me. @1-liners/maintainers?

(Closes #108)

**Comment by huei90** [comment]
What's the meaning of :ship: to me?

I can't access the page maintainer.

Yup, I love this project and giving me a lot of ideas and inspirations.

**Comment by davidchase** [comment]
looks ready to ship? with a ship picture?

**Comment by huei90** [comment]
Now i get it. :smile:

**Comment by stoeffel** [comment]
Awesome work!

**Pull request merged**
