### PR TITLE
added composeAll()

### PR DESCRIPTION
**Pull request by guumaster**
I don't know about function readability and it doesn't have a fixed number of parameter.

### CODE REVIEW

**Comment by stoeffel** [comment]
Same here this should take an array of functions.

How about something like this: http://jsbin.com/hapika/edit?js,console

**Comment by guumaster** [comment]
:+1: much better

**Comment by stoeffel** [comment]
LGTM. could you squash your commits? thx

**Comment by guumaster** [comment]
squashed

**Comment by stoeffel** [comment]
Thx

**Pull request merged**
