### PR TITLE
adds lt, gt, le, ge

### LINKED ISSUE #52: lower and greater than
- [ ] lt
- [ ] gt
- [ ] le
- [ ] ge

### PR DESCRIPTION
**Pull request by stoeffel**
closes #52

:checkered_flag:

### CODE REVIEW

**Comment by stoeffel** [comment]
//cc @tomekwi @hemanth how do you like the names of this functions? Expressive enough?

**Comment by hemanth** [comment]
yup :)

**Comment by tomekwi** [comment]
I prefer explicit names like `lessThan` to cryptic shortcuts like `lt` inherited from the dawn of the Unix epoch.

This makes it easier to read code. And with a decent text editor typing `lessThan` is no more labor than `lt`.

But I’m fine either way.

**Comment by hemanth** [comment]
Should we give the user a privilege to alias them?

**Comment by stoeffel** [comment]
IMO Users can just do:

```js
var lt = require('1-liners/lowerThan');
var lowerThan = require('1-liners/lowerThan');
```

**Comment by stoeffel** [comment]
I moved to lessOrEqual and lessThan since its 1 character less :smile:

**Comment by stoeffel** [comment]
:checkered_flag:

**Comment by tomekwi** [comment]
:+1:

**Pull request merged**
