### PR TITLE
Specify and add `between`

### PR DESCRIPTION
**Pull request by tomekwi**
### between

Return `number` if it’s greater than `min` and lower than `max`. Else return `min` or `max` respectively.

```js
var between = require('1-liners/between');

between(1, 10, 2.5);  // => 2.5
between(1, 10, -5);   // => 1
between(1, 10, 25);   // => 10
```

<div align="right"><sup>
	<a href="../tests/between.js">Spec</a>
	•
	<a href="../module/between.js">Source</a>: <code> (min, max, number) =&gt; (number &lt; min ? min : (number &gt; max ? max : number));</code>
</sup></div>

### CODE REVIEW

**Comment by tomekwi** [comment]
:checkered_flag:

**Comment by stoeffel** [comment]
Only from the name of the function I personally would expect the result to be:

```js
between(1, 10, 2.5);  // => true
between(1, 10, -5);   // => false
between(1, 10, 25);   // => false
```

hmm or maybe we could keep this behaviour and add a `isBetween`?

**Comment by hemanth** [comment]
'isBetween' :+1:

**Comment by tomekwi** [comment]
Said, done :)

**Pull request merged**
